name: Update Days Since
on:
  schedule:
    - cron: "*/30 * * * *" 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate days
        run: |
          start_date="2023-09-05"
          today=$(date +%Y-%m-%d)
          days=$(date -d "$today" +%j)
          start_days=$(date -d "$start_date" +%j)
          days_passed=$((days - start_days))
          echo "Days passed: $days_passed"
      - name: Update README.md
        run: |
          sed -i 's/{day_placeholder}/'"$days_passed"'/g' README.md
