name: Update README

on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate days and update README with Python
        run: |
          python -c "
          import datetime

          days_elapsed = str((datetime.datetime.now() - datetime.datetime(2023, 9, 5)).days)
          file_name = 'README.md'

          try:
              with open(file_name, 'r') as file:
                  content = file.read()
                  content = content.replace('placeholder', days_elapsed)

              with open(file_name, 'w') as file:
                  file.write(content)

          except FileNotFoundError:
              print('File not found.')
          except Exception:
              print('An error occurred.')
          "

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update day counter"
          file_pattern: README.md
