name: Update README

on: 
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Calculate days and update README
        run: |
          import datetime

          start_date = datetime.date(2023, 9, 5)
          today = datetime.date.today()
          days_passed = (today - start_date).days

          with open('README.md', 'r') as f:
            readme = f.read()

          updated_readme = readme.replace('{day_placeholder}', str(days_passed))

          with open('README.md', 'w') as f:
            f.write(updated_readme)

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update day counter"
          file_pattern: README.md
